version: '3.9'

services:
  mysql-bank-credit:
    image: mysql:8.0
    container_name: container_mysql_bank_credit
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_credit_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-bank-credit
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-bank-credit
    restart: unless-stopped

  app-bank-credit-backend:
    image: app-bank-credit
    container_name: container-bank-credit
    ports:
      - 8082:8081
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://mysql-bank-credit:3306/bank_credit_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      spring.datasource.username: user
      spring.datasource.password: user
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xmx64M
    depends_on:
      - mysql-bank-credit
    links:
      - mysql-bank-credit

volumes:
  mysql_data:
    driver: local